language: node_js
node_js:
  - v12.18.3
cache:
  directories:
      - "node_modules"
env:
  - DATABASE_HOST=localhost MYSQL_DATABASE=cherrytwist MYSQL_ROOT_PASSWORD=toor AUTHENTICATION_ENABLED=false
install:
  - npm install
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cherrytwist;'
  - mysql -e 'ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'toor';'
script:
  - npm run-script test:e2e
