language: node_js
node_js:
  - v12.18.3
cache:
  directories:
      - "node_modules"
install:
  - npm install
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cherrytwist;'
before_script:
  - npm run-script prebuild
  - npm run-script build
  - echo "USE mysql;\nALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'toor';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - npm run-script test:e2e
