language: node_js
node_js:
  - v12.18.3
cache:
  directories:
      - "node_modules"
env:
  - DATABASE_HOST=localhost MYSQL_DATABASE=cherrytwist MYSQL_ROOT_PASSWORD=toor AUTHENTICATION_ENABLED=false
install:
  - npm install
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cherrytwist;'
before_script:
  - echo "USE mysql;\nUPDATE mysql.user SET authentication_string= 'toor' WHERE User = 'root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - npm run-script test:e2e
