version: '3.4'

networks:
  ct:

services:
  server.node:
    container_name: ct_server
    image: server.node
    build: .
    networks:
      - ct
    environment:
      - DATABASE_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    depends_on:
      - db
    restart: always
    ports:
      - 4000:4000
    command: ["npm", "start"]
  db:
    container_name: ct_server_db
    image: mysql:8.0.11
    networks:
      - ct
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
        