kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: ct-server-deployment
  labels:
    app: ct-server

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ct-server
  template:
    metadata:
      labels:
        app: ct-server
    spec:
      containers:
        - name: ct-server
          image: cherrytwist/server:0.1.2
          ports:
            - name: graphql
              containerPort: 4000

