kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: ct-server-deployment
  labels:
    app: ct-server

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ct-server
  template:
    metadata:
      labels:
        app: ct-server
    spec:
      containers:
        - name: ct-server
          image: ctdev.azurecr.io/ct-server:71719063d15910e5ad6e43c1083e1721b638787a
          envFrom:
          - secretRef:
              name: wait-hosts
          - secretRef:
              name: server-secret
          ports:
            - name: graphql
              containerPort: 4000

